[versions]
kotlin = "2.2.21"
kotlin-serialization = "1.9.0"
junit = "6.0.1"
slf4j = "2.0.17"
kotlinx-benchmark = "0.4.15"

[libraries]
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }

# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
instancio-junit = { module = "org.instancio:instancio-junit", version = "5.5.1" }
jtoon = { module = "dev.toonformat:jtoon", version = "1.0.7" }
kotlinToon = { module = "br.com.vexpera:kotlin-toon", version = "1.0.0"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "kotlinx-benchmark" }

# Unversioned plugins for subprojects
kotlin-jvm-base = { id = "org.jetbrains.kotlin.jvm" }
kotlin-serialization-base = { id = "org.jetbrains.kotlin.plugin.serialization" }
kotlinx-benchmark-base = { id = "org.jetbrains.kotlinx.benchmark" }
